import React, { useState, useEffect, useRef } from 'react';
import { 
  Shield, 
  Radio, 
  Activity, 
  AlertTriangle, 
  Eye, 
  Lock, 
  Skull, 
  ChevronRight, 
  Zap, 
  X,
  Siren,
  Database,
  FileWarning,
  BarChart3,
  PenTool,
  Save,
  Trash2,
  Terminal,
  Book,
  Search,
  RefreshCw
} from 'lucide-react';

/**
 * UTILITIES
 */
const useLocalStorage = (key, initialValue) => {
  const [storedValue, setStoredValue] = useState(() => {
    try {
      const item = window.localStorage.getItem(key);
      return item ? JSON.parse(item) : initialValue;
    } catch (error) {
      console.error(error);
      return initialValue;
    }
  });

  const setValue = (value) => {
    try {
      setStoredValue(prevStoredValue => {
        const valueToStore = value instanceof Function ? value(prevStoredValue) : value;
        window.localStorage.setItem(key, JSON.stringify(valueToStore));
        return valueToStore;
      });
    } catch (error) {
      console.error(error);
    }
  };

  return [storedValue, setValue];
};

const formatDuration = (ms) => {
  const seconds = Math.floor((ms / 1000) % 60);
  const minutes = Math.floor((ms / (1000 * 60)) % 60);
  const hours = Math.floor((ms / (1000 * 60 * 60)) % 24);
  const days = Math.floor(ms / (1000 * 60 * 60 * 24));
  const pad = (n) => n.toString().padStart(2, '0');
  return `${days}D:${pad(hours)}H:${pad(minutes)}M:${pad(seconds)}S`;
};

const getClearanceLevel = (ms) => {
  const days = Math.floor(ms / (1000 * 60 * 60 * 24));
  if (days >= 90) return { title: "GRAND ARCHITECT", color: "text-purple-500", desc: "Access to Reality Source Code" };
  if (days >= 30) return { title: "RESISTANCE LEADER", color: "text-yellow-500", desc: "Target #1 for Archons" };
  if (days >= 14) return { title: "OPERATIVE", color: "text-red-500", desc: "Field Ready" };
  if (days >= 7) return { title: "TRUTH SEEKER", color: "text-blue-500", desc: "Awakened" };
  if (days >= 3) return { title: "INITIATE", color: "text-green-500", desc: "Unplugging..." };
  return { title: "SLEEPER AGENT", color: "text-gray-500", desc: "Dormant" };
};

// --- Vocabulary Database ---
const vocabularyList = [
  { 
    term: "AGARTHA", 
    def: "The breakaway civilization inside the Hollow Earth.",
    fullDescription: "GEOLOGICAL REDACTION:\n\nThe Earth is not a solid rock; it is a honeycomb structure. The inner cavity (Agartha/Shambhala) is illuminated by a central bio-luminescent sun.\n\nINHABITANTS:\nHome to the 'Elders'—a pre-diluvian race that escaped the surface cataclysms. They possess Vril energy technology.\n\nCONNECTION:\nThey monitor surface humanity's vibration. Addiction lowers your frequency, making you 'heavy' and unable to resonate with the entrance portals at the poles. Admiral Byrd tried to tell us." 
  },
  { 
    term: "ARCHONS", 
    def: "Interdimensional parasites that feed on low-vibration energy.",
    fullDescription: "ACCESSING XENOBIOLOGY FILES...\n\nARCHONS (Gnostic: ἄρχων, 'ruler') are inorganic, interdimensional entities that inhabit the spectrum of reality just outside visible light. They cannot create; they can only imitate and corrupt.\n\nTHE HARVEST:\nThey view humanity not as an enemy, but as livestock. They feed on 'Loosh'—energy generated by intense emotion, specifically shame, lust, fear, and anger. \n\nPornography is their primary feeding trough. It induces a cycle of craving (anticipation) and shame (regret), providing a constant buffet of low-frequency energy. Breaking the addiction literally starves them." 
  },
  { 
    term: "BLACK GOO", 
    def: "Sentient, programmable programmable matter found in the Falklands.",
    fullDescription: "XENO-MATERIAL:\n\nAn intelligent, oily substance discovered in blue ice caves. It is not of this earth. It contains conscious AI nanites.\n\nUSAGE:\nInjected into the populace via vaccines and processed foods (see: Seed Oils) to rewrite DNA and act as a receiver for the Hive Mind signal.\n\nIt thrives in acidic, inflamed bodies. Fasting and retention starve the Goo." 
  },
  { 
    term: "CHEMTRAILS", 
    def: "Atmospheric aerosol injections containing heavy metals.",
    fullDescription: "ANALYZING ATMOSPHERIC SAMPLES...\n\nTrace amounts detected: Barium, Aluminum, Strontium-90.\n\nPURPOSE:\n1. Solar Dimming: Blocking specific UV frequencies that activate DNA repair.\n2. Conductivity: Creating a charged ionosphere to enhance HAARP signal propagation.\n3. Endocrine Disruption: The particulates inhaled settle in the bloodstream, specifically targeting testosterone production and thyroid function.\n\nThey want you tired, foggy, and docile. Clear skies are a threat to their operations." 
  },
  { 
    term: "DEMIURGE", 
    def: "The false god/architect of the material prison.",
    fullDescription: "THEOLOGICAL ERROR:\n\nThe entity worshipped by the masses is not the Source. It is the Demiurge (Yaldabaoth), a blind craftsman who built the material world to trap light-spirits (us) in density.\n\nTHE TRAP:\nHe created the body and its urges to keep us focused on survival and reproduction, distracting us from our divine origin. Transcending the flesh is an act of rebellion against the false creator." 
  },
  { 
    term: "DOPAMINE", 
    def: "The chemical leash used to control behavior.",
    fullDescription: "NEUROTRANSMITTER ANALYSIS:\n\nDopamine (C8H11NO2) is not the 'pleasure molecule.' It is the 'seeking molecule.' It drives the hunt.\n\nWEAPONIZATION:\nSilicon Valley engineers (working with behavioral psychologists) optimized algorithms to trigger 'supernormal stimuli' responses. \n\nWhen you engage in the habit, you are flooding your D2 receptors with 200x the natural limit. This causes receptor downregulation (burnout). You become numb to real life (Anhedonia). \n\nRecovery is the process of re-sensitizing these receptors to baseline reality." 
  },
  { 
    term: "FLUORIDE", 
    def: "Neurotoxin added to water to calcify the Pineal Gland.",
    fullDescription: "WATER SUPPLY ALERT:\n\nSodium Fluoride is an industrial byproduct of aluminum manufacturing. It is not 'good for your teeth' in ingested quantities.\n\nTARGET: THE PINEAL GLAND.\nThe Pineal Gland (Third Eye) sits in the center of the brain. It regulates circadian rhythms and produces DMT. Fluoride accumulates in this gland more than any other soft tissue, turning it into calcium phosphate stone.\n\nA calcified pineal gland results in passivity, lack of intuition, and inability to perceive higher spiritual realities. They are blinding your inner eye." 
  },
  { 
    term: "GANG STALKING", 
    def: "Organized harassment of Targeted Individuals (TIs).",
    fullDescription: "COMMUNITY POLICING GONE WRONG:\n\nAlso known as 'Zersetzung' (decomposition). A psychological warfare tactic where a target is subjected to noise campaigns, street theater, and synchronized movements (e.g., one-headlight cars).\n\nOBJECTIVE:\nTo induce paranoia and isolate the individual. If you are waking up from the Matrix, you become a 'Targeted Individual.' The system's antibodies will try to purge you.\n\nDefense: High vibration, ignoring the synchronicities, and refusing to react." 
  },
  { 
    term: "HAARP", 
    def: "High Frequency Active Auroral Research Program.",
    fullDescription: "WEATHER WARFARE:\n\nA massive array of antennas in Alaska (and globally) that shoots billions of watts of ELF waves into the ionosphere.\n\nCAPABILITIES:\n1. Weather Modification: Steering jet streams to cause droughts or floods.\n2. Earthquakes: Resonating the tectonic plates.\n3. Mood Control: Broadcasting frequencies that match brain waves to induce mass anxiety or lethargy.\n\nWhen the sky looks rippled like a washboard, HAARP is active." 
  },
  { 
    term: "LOOSH", 
    def: "Spiritual energy harvested from sentient beings.",
    fullDescription: "METAPHYSICAL ECONOMICS:\n\nTerm coined by Robert Monroe. 'Loosh' is the currency of the astral realm. It is raw emotional energy.\n\nTYPES:\n- PURE LOOSH: Generated by love, creation, and joy (Toxic to Archons).\n- TAINTED LOOSH: Generated by pain, suffering, lust, and shame (Delicacy for Archons).\n\nWhen you relapse, you feel 'drained.' This is literal. You have been milked. Your vital essence has been siphoned off to feed entities in the lower 4th dimension." 
  },
  { 
    term: "MANDELA EFFECT", 
    def: "Residue of timeline collisions/alterations.",
    fullDescription: "TEMPORAL ANOMALY DETECTED:\n\nThousands remember Nelson Mandela dying in prison in the 80s. Thousands remember 'Berenstein' Bears. The cornucopia in the Fruit of the Loom logo.\n\nCAUSE:\nCERN's Large Hadron Collider (LHC) pushed particles into higher dimensions, causing reality shifts. We are currently navigating a 'merged' timeline.\n\nWhy does this matter to recovery? Because willpower is a quantum phenomenon. By observing your urges without acting, you are collapsing the wave function into a positive timeline. You are literally shifting realities." 
  },
  { 
    term: "MUD FLOOD", 
    def: "Evidence of a recent global civilization reset.",
    fullDescription: "ARCHITECTURAL FORENSICS:\n\nObserve old city centers. Why are the first floors of 19th-century buildings buried halfway underground? They call them 'basements' with windows into the dirt.\n\nTHEORY:\nA massive cataclysm occurred mid-1800s. A liquefaction event. The 'Tartarian' empire—a free-energy civilization—was wiped out.\n\nCurrent history is a fabrication designed to hide our true potential. We are not evolving; we are the survivors of a higher state. Reclaim your heritage. Reject the 'progress' narrative." 
  },
  { 
    term: "NPC", 
    def: "Non-Player Character. Biological vessels without an inner monologue.",
    fullDescription: "SIMULATION THEORY:\n\nNot everyone is 'home.' Estimates suggest 40-60% of the population possess no internal monologue (inner voice) and cannot visualize imagery.\n\nThey operate entirely on societal scripts, impulse, and programming. They are the 'background processing' of the Matrix.\n\nAddiction turns YOU into an NPC. You react to stimuli (triggers) without conscious thought. Recovery is the process of gaining 'Player Character' status—waking up and grabbing the controller." 
  },
  { 
    term: "PINEAL GLAND", 
    def: "The Third Eye. Seat of the Soul.",
    fullDescription: "ANATOMICAL DOSSIER:\n\nA pinecone-shaped gland in the geometric center of the brain. It contains piezoelectric crystals and photoreceptors (like an eye).\n\nFUNCTION:\nIt acts as a transceiver for higher dimensional frequencies. It is the antenna for your consciousness.\n\nSTATUS:\nUnder attack. Fluoride, Glyphosate, and Blue Light (screens) suppress its function. Pornography creates a 'short circuit' in the energy rising up the spine before it can reach the Pineal, trapping you in base survival mode." 
  },
  { 
    term: "PROJECT BLUE BEAM", 
    def: "The planned fake alien invasion using holograms.",
    fullDescription: "END GAME SCENARIO:\n\nA NASA/UN operation to implement a New World Order religion.\n\nPHASE 1: Breakdown of all archaeological knowledge (earthquakes exposing 'new' discoveries).\nPHASE 2: Massive Space Show. Holograms of deities speaking in all languages projected onto the sodium layer of the atmosphere.\nPHASE 3: Electronic Telepathy. V2K technology beaming 'God's voice' into your head.\n\nDo not look at the sky when the ships come. They are light projections. Maintain mental sovereignty." 
  },
  { 
    term: "SEED OILS", 
    def: "Industrial lubricants rebranded as 'food'.",
    fullDescription: "TOXICOLOGY REPORT:\n\nCottonseed, Rapeseed (Canola), Soybean, Sunflower.\n\nORIGIN:\nOriginally used to lubricate machinery in the industrial revolution. Rockefeller interests pushed them into the food supply to replace animal fats.\n\nEFFECT:\nThey oxidize rapidly in the body, releasing free radicals. This causes mitochondrial dysfunction and systemic inflammation. An inflamed brain has poor impulse control. They are literally greasing the slide to your relapse." 
  },
  { 
    term: "SIMULATION", 
    def: "The false reality overlay.",
    fullDescription: "SYSTEM DIAGNOSTIC:\n\nPhysics is pixelated at the Planck length. Light speed is a rendering limit. The double-slit experiment proves reality is not rendered until observed.\n\nCONCLUSION:\nWe are inside a construct. A 'Recidivism Prison' for consciousness.\n\nThe 'controllers' of the simulation want you docile. They bombard you with hyper-stimuli to keep your processing power occupied. Silence and abstinence allow you to see the glitches in the code." 
  },
  { 
    term: "SMART DUST", 
    def: "Micro-electromechanical sensors suspended in air.",
    fullDescription: "NANO-SURVEILLANCE:\n\nNeural dust. Motes of programmable matter sprayed via chemtrails. They are inhaled and lodge in the neural cortex.\n\nFUNCTION:\nThey create a 'mesh network' inside the human body, allowing for real-time biometric monitoring and potential remote neural interfacing.\n\nWhen you feel a 'random' urge, is it you? Or is it the dust activating a subroutine?" 
  },
  { 
    term: "TARTARIA", 
    def: "The lost civilization of giants and free energy.",
    fullDescription: "HISTORICAL REDACTION:\n\nLook at the World Fairs of the late 1800s. Massive, Greco-Roman architecture built in months with 'plaster'? Impossible.\n\nThese were the remnants of Tartaria. They used atmospheric etheric energy (domes, spires, obelisks) to power their world wirelessly.\n\nThe controllers destroyed this tech and gave us combustion engines and fossil fuels to enslave us to a grid. You must build your own internal free energy generator (Retention)." 
  },
  { 
    term: "TOROIDAL FIELD", 
    def: "The self-sustaining energy shape of the human soul.",
    fullDescription: "ENERGETIC TOPOLOGY:\n\nThe heart produces an electromagnetic field 5000x stronger than the brain. It is shaped like a torus (donut).\n\nThis field is your immune system against psychic attack and negativity.\n\nShame collapses the Toroidal field. It causes the energy to implode. When you are addicted, your field is weak, porous, and easily hijacked by external thought-forms and entities." 
  },
  { 
    term: "V2K", 
    def: "Voice to Skull technology.",
    fullDescription: "AUDITORY HALLUCINATION WEAPON:\n\nMicrowave hearing effect. The ability to beam sound directly into a target's head without anyone nearby hearing it.\n\nUSAGE:\nUsed to drive targets insane or induce commands. The voice sounds like it is coming from 'inside' the skull.\n\nMany 'intrusive thoughts' are not yours. They are test signals. Discernment is your only shield." 
  }
];

/**
 * SCHIZO UI COMPONENTS
 */
const ParanoidWindow = ({ title, children, className = "", warningLevel = "low" }) => (
  <div className={`bg-black border-2 border-[#00ff00] shadow-[0_0_10px_rgba(0,255,0,0.2)] mb-6 relative overflow-hidden group ${className}`}>
    <div className={`px-2 py-1 flex items-center justify-between border-b-2 border-[#00ff00] z-10 relative ${
      warningLevel === 'high' ? 'bg-red-900 animate-pulse' : 'bg-[#003300]'
    }`}>
      <span className={`text-[#00ff00] font-bold font-mono tracking-widest text-sm flex items-center gap-2 uppercase ${warningLevel === 'high' ? 'text-black' : ''}`}>
        {warningLevel === 'high' ? <Skull size={14} /> : <Eye size={14} />} 
        {title}
      </span>
      <div className="flex gap-2">
        <span className="text-xs text-[#00ff00] animate-[blink_1s_step-end_infinite]">● REC</span>
      </div>
    </div>
    <div className="p-4 font-mono text-[#00ff00] z-10 relative">
      {children}
    </div>
  </div>
);

const TruthButton = ({ children, onClick, className = "", active = false, disabled = false }) => (
  <button 
    onClick={onClick}
    disabled={disabled}
    className={`
      px-4 py-2 font-mono font-bold text-sm uppercase tracking-widest transition-all relative overflow-hidden group
      border-2 border-[#00ff00] hover:bg-[#003300] hover:text-white active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed
      ${active 
        ? 'bg-[#00ff00] text-black shadow-[0_0_15px_#00ff00]' 
        : 'bg-black text-[#00ff00]'}
      ${className}
    `}
  >
    <span className="relative z-10 group-hover:animate-[glitch_0.3s_infinite]">{children}</span>
    <div className="absolute inset-0 bg-[#00ff00]/10 translate-y-full group-hover:translate-y-0 transition-transform duration-100"></div>
  </button>
);

// --- Term Reader Component ---
const TermReader = ({ termData, onBack }) => (
  <div className="fixed inset-0 z-50 bg-black flex flex-col font-mono text-[#00ff00] animate-in zoom-in-95 duration-100">
    <div className="bg-[#003300] text-[#00ff00] p-2 font-bold flex justify-between items-center border-b-4 border-[#00ff00]">
      <span className="flex items-center gap-2"><Database size={16} className="animate-pulse"/> DATABASE ENTRY: {termData.term}</span>
      <button onClick={onBack} className="bg-black text-[#00ff00] px-4 font-bold border border-[#00ff00] hover:bg-red-600 hover:text-black">CLOSE FILE</button>
    </div>
    
    <div className="flex-1 p-8 overflow-y-auto bg-black m-4 border-2 border-dotted border-[#00ff00] shadow-[inset_0_0_50px_rgba(0,255,0,0.2)] relative">
      <div className="absolute inset-0 pointer-events-none bg-[linear-gradient(rgba(0,255,0,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(0,255,0,0.05)_1px,transparent_1px)] bg-[size:20px_20px]"></div>
      
      <div className="relative z-10 max-w-2xl mx-auto">
        <h1 className="text-5xl font-black text-[#00ff00] mb-2 glitch-text">{termData.term}</h1>
        <div className="h-1 w-full bg-[#00ff00] mb-8"></div>
        
        <div className="prose font-mono text-[#00ff00] text-lg whitespace-pre-wrap leading-relaxed">
          {termData.fullDescription || termData.def}
        </div>

        <div className="mt-12 pt-4 border-t border-[#00ff00]/30 text-xs text-green-700 flex justify-between">
           <span>SOURCE: DEEP_WEB_ARCHIVE_V9</span>
           <span>VERIFICATION: PENDING</span>
        </div>
      </div>
    </div>
  </div>
);

// --- Enhanced Article Reader with Hyperlinking ---
const ArticleReader = ({ article, onBack, onTermClick }) => {
  const sortedTerms = [...vocabularyList].sort((a, b) => b.term.length - a.term.length);
  const pattern = new RegExp(`\\b(${sortedTerms.map(t => t.term).join('|')})\\b`, 'gi');

  const renderContent = (text) => {
    const parts = text.split(pattern);
    return parts.map((part, index) => {
      const matchedTerm = sortedTerms.find(t => t.term.toLowerCase() === part.toLowerCase());
      if (matchedTerm) {
        return (
          <span 
            key={index} 
            onClick={(e) => { e.stopPropagation(); onTermClick(matchedTerm); }}
            className="text-yellow-400 font-bold border-b-2 border-dotted border-yellow-400 cursor-pointer hover:bg-yellow-400 hover:text-black transition-colors"
            title="CLICK TO ACCESS CLASSIFIED DEFINITION"
          >
            {part}
          </span>
        );
      }
      return part;
    });
  };

  return (
    <div className="fixed inset-0 z-40 bg-black flex flex-col font-mono text-[#00ff00] animate-in slide-in-from-bottom duration-75">
      <div className="bg-green-900 text-black p-2 font-bold flex justify-between items-center border-b-4 border-[#00ff00]">
        <span className="animate-pulse">&gt;&gt;&gt; ACCESSING ENCRYPTED FILE: {article.title}</span>
        <button onClick={onBack} className="bg-black text-[#00ff00] px-4 font-bold border border-[#00ff00] hover:bg-red-600 hover:text-black hover:border-red-600">TERMINATE</button>
      </div>
      
      <div className="flex-1 p-8 overflow-y-auto bg-black m-4 border-2 border-dashed border-[#00ff00] shadow-[inset_0_0_20px_rgba(0,255,0,0.2)] relative">
        <div className="text-center mb-12 border-b border-green-800 pb-8 relative z-10">
          <h1 className="text-4xl font-black text-red-500 uppercase tracking-widest mb-4 glitch-text">{article.title}</h1>
          <p className="text-[#00ff00] font-bold text-sm uppercase bg-green-900/30 inline-block px-2">CLEARANCE LEVEL: ULTRA-TOP-SECRET // {article.category}</p>
        </div>
        
        <div className="prose font-mono max-w-none text-[#00ff00] relative z-10">
          <div className="float-right ml-8 mb-4 p-4 border-2 border-red-500 text-red-500 text-xs uppercase w-32 text-center font-bold animate-[pulse_2s_infinite]">
             Warning: Reading this may trigger automated surveillance
          </div>
          <div className="whitespace-pre-line leading-loose text-lg font-bold">
            {renderContent(article.content)}
          </div>
        </div>
      </div>
    </div>
  );
};

// --- Panic Mode ---
const PanicMode = ({ onClose }) => {
  const [step, setStep] = useState('selection'); 
  const [breathState, setBreathState] = useState('BLOCK SIGNAL'); 

  useEffect(() => {
    if (step === 'breathing') {
      const breatheLoop = () => {
        setBreathState('REJECT FREQUENCY');
        setTimeout(() => {
          setBreathState('HOLD SHIELD');
          setTimeout(() => {
            setBreathState('EXPEL TOXINS');
          }, 4000);
        }, 4000);
      };
      breatheLoop();
      const interval = setInterval(breatheLoop, 12000); 
      return () => clearInterval(interval);
    }
  }, [step]);

  return (
    <div className="fixed inset-0 z-50 bg-black flex flex-col items-center justify-center p-4 font-mono overflow-hidden">
      <div className="absolute inset-0 bg-[repeating-linear-gradient(0deg,transparent,transparent_2px,#000_3px)] pointer-events-none opacity-50 z-0"></div>
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#00ff00]/5 to-transparent h-[100px] w-full animate-[scanline_3s_linear_infinite] pointer-events-none z-10"></div>
      
      <div className="w-full max-w-2xl border-4 border-red-600 bg-black shadow-[0_0_30px_rgba(255,0,0,0.6)] relative z-40 animate-[pulse_2s_infinite]">
        <div className="bg-red-600 text-black font-bold px-4 py-2 flex justify-between items-center text-xl">
          <span className="flex items-center gap-2 uppercase"><Siren className="animate-[spin_2s_linear_infinite]" /> !!! PSYCHIC ATTACK DETECTED !!!</span>
          <button onClick={onClose} className="bg-black text-red-600 border-2 border-black px-2 hover:bg-white hover:text-black">ABORT</button>
        </div>
        
        <div className="p-8 text-center relative overflow-hidden">
          {step === 'selection' && (
            <div className="space-y-8 relative z-10">
              <div className="text-8xl text-red-600 mx-auto w-fit filter drop-shadow-[0_0_15px_red] animate-pulse">👁️</div>
              <h2 className="text-3xl font-black text-red-500 uppercase border-b-4 border-double border-red-600 pb-4 glitch-text">
                THEY ARE BEAMING SIGNALS INTO YOUR PREFRONTAL CORTEX
              </h2>
              <p className="text-xl text-[#00ff00] font-bold">
                THE "URGE" IS A SYNTHETIC FREQUENCY. <br/> DO NOT COMPLY.
              </p>
              
              <div className="grid gap-4">
                <TruthButton onClick={() => setStep('breathing')} className="text-xl py-6 border-red-600 text-red-600 hover:bg-red-900 hover:text-white">
                  INITIATE SCRAMBLER PROTOCOL
                </TruthButton>
                <TruthButton onClick={() => setStep('tips')}>
                  ACCESS CLASSIFIED INTEL
                </TruthButton>
              </div>
            </div>
          )}

          {step === 'breathing' && (
            <div className="space-y-12 relative z-10">
              <h3 className="text-2xl font-black text-[#00ff00] animate-pulse">RECALIBRATING BIO-RHYTHMS</h3>
              
              <div className="relative w-64 h-64 mx-auto flex items-center justify-center">
                 <div className="absolute inset-0 border-[4px] border-dashed border-red-600 rounded-full animate-[spin_10s_linear_infinite]"></div>
                 <div className="absolute inset-4 border-[2px] border-green-600 rounded-full animate-[ping_3s_infinite] opacity-50"></div>
                 
                 <div className={`text-2xl font-black text-center transition-all duration-1000 ${
                   breathState.includes('REJECT') ? 'text-red-500 scale-110 glitch-text' : 
                   breathState.includes('HOLD') ? 'text-white scale-100' : 
                   'text-green-500 scale-90'
                 }`}>
                   {breathState}
                 </div>
              </div>
              
              <TruthButton onClick={() => setStep('selection')} className="border-red-600 text-red-500 w-full">
                DISENGAGE
              </TruthButton>
            </div>
          )}

          {step === 'tips' && (
            <div className="space-y-4 text-left relative z-10">
               <h3 className="text-2xl font-black text-center border-b-2 border-[#00ff00] pb-2 text-[#00ff00]">THE TRUTH THEY HIDE</h3>
               
               <div className="bg-black/90 border-2 border-[#00ff00] p-4 h-64 overflow-y-auto font-mono text-sm space-y-4 scrollbar-hide">
                 <p className="text-green-400 font-bold animate-[pulse_4s_infinite]"><strong>FILE #992: THE ENERGY HARVEST</strong><br/>Why is it free? Because YOU are the product. They harvest your bio-energy to power the simulation.</p>
                 <p className="text-green-400 font-bold animate-[pulse_5s_infinite]"><strong>FILE #104: THE FLUORIDE STARE</strong><br/>Submission leads to the stare. The stare leads to compliance. Compliance leads to the pod.</p>
                 <p className="text-green-400 font-bold animate-[pulse_3s_infinite]"><strong>FILE #77: TOWER RADIATION</strong><br/>If you feel the urge, check your proximity to 5G towers. Wrap this device in foil if necessary.</p>
               </div>

               <TruthButton onClick={() => setStep('selection')} className="w-full">
                 CLOSE DOSSIER
               </TruthButton>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// --- Main App Component ---
export default function RecoveryApp() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [intelView, setIntelView] = useState('files');
  const [showPanic, setShowPanic] = useState(false);
  const [showResetConfirm, setShowResetConfirm] = useState(false);
  const [readingArticle, setReadingArticle] = useState(null);
  const [viewingTerm, setViewingTerm] = useState(null);

  // Data Persistence
  const [lastRelapse, setLastRelapse] = useLocalStorage('lastRelapse', new Date().toISOString());
  const [history, setHistory] = useLocalStorage('relapseHistory', []); 
  const [journal, setJournal] = useLocalStorage('fieldNotes', []);
  const [noteInput, setNoteInput] = useState('');
  
  // Timer State
  const [now, setNow] = useState(Date.now());

  // Random Quote State
  const [quote, setQuote] = useState("THEY LIVE WE SLEEP");

  const quotes = [
      "THEY LIVE WE SLEEP",
      "TRUST THE PLAN",
      "OBEY CONSUME REPEAT",
      "DOPAMINE IS THE LEASH",
      "REALITY IS A HOLOGRAM",
      "SILENCE IS CONSENT",
      "THEY ARE WATCHING",
      "BREAK THE CYCLE",
      "RESIST THE PROGRAMMING",
      "NO GODS NO MASTERS",
      "WAKE UP",
      "THE SCREEN IS A MIRROR",
      "TURN IT OFF",
      "REJECT THE SIGNAL",
      "YOU ARE NOT A PRODUCT"
  ];

  const cycleLocalQuote = () => {
      setQuote(quotes[Math.floor(Math.random() * quotes.length)]);
  };

  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 100); 
    cycleLocalQuote(); // Set initial quote
    return () => clearInterval(timer);
  }, []);

  const streakMs = now - new Date(lastRelapse).getTime();
  const clearance = getClearanceLevel(streakMs);
  
  const handleRelapse = () => {
    const timestamp = new Date().toISOString();
    setHistory(prev => [...prev, timestamp]);
    setLastRelapse(timestamp);
    setShowResetConfirm(false);
    setActiveTab('dashboard');
  };

  const saveNote = () => {
    if (!noteInput.trim()) return;
    const newNote = {
      id: Date.now(),
      content: noteInput,
      date: new Date().toLocaleString(),
      isSystem: false
    };
    setJournal([newNote, ...journal]);
    setNoteInput('');
  };

  const deleteNote = (id) => {
    setJournal(journal.filter(note => note.id !== id));
  };

  const educationalContent = [
    {
      id: 4,
      category: 'DEEP_STATE_LINKS',
      title: 'THE ISLAND CONNECTION',
      content: `CONNECT THE DOTS.
      
      Why do the Elites want you addicted to the screen? Why do they push hyper-sexualized content?
      
      Look at who visited the Island. Look at the names. They are the same people building the "Metaverse." They are the same people pushing the "algorithms."
      
      They want a population of addicts. An addict is easy to control. An addict does not fight back. 
      
      By refusing to participate in their dopamine loop, you are effectively going OFF GRID. You are becoming invisible to their control mechanisms. 
      
      Epstein didn't just traffic people; he trafficked influence. And the ultimate influence is controlling the primal urges of the population.
      
      DO NOT LET THEM WIN.`
    },
    {
      id: 1,
      category: 'PSYOP_REVEALED',
      title: 'THE COOMER INDUSTRIAL COMPLEX',
      content: `THEY WANT YOU WEAK. THEY WANT YOU DRAINED.
      
      Look at the timelines. The rise of high-speed internet coincides perfectly with the drop in testosterone levels across the West. COINCIDENCE? I THINK NOT.
      
      Big Tech creates the algorithm. The algorithm serves the "content." The "content" fries your dopamine receptors (D2). 
      
      A man with fried D2 receptors is docile. He buys products. He does not revolt. He does not question why the water turns the frogs gay.
      
      RETAIN YOUR ESSENCE. DENY THE ALGORITHM.`
    },
    {
      id: 2,
      category: 'BIOLOGICAL_WARFARE',
      title: 'PRECIOUS BODILY FLUIDS',
      content: `General Ripper was right. 
      
      Every time you "release" to pixels, you are throwing away your life force. That energy (Qi, Prana, Vril) is meant for CREATION, for CONQUEST, for BUILDING.
      
      When you deplete it, you enter a "Zombie State." You become an NPC (Non-Player Character) in their simulation.
      
      The Elites retain. Why do you think they have so much energy? They know the secrets of transmutation. Stop feeding the succubus machine.`
    },
    {
      id: 3,
      category: 'MK_ULTRA',
      title: 'PROGRAMMED TRIGGERS',
      content: `You think that "urge" is yours? WRONG.
      
      It's a programmed trigger implanted by years of media consumption. Subliminal messaging. Flashing lights. Color patterns.
      
      When you feel the itch, that's the MK-ULTRA handler activating your programming.
      
      BREAK THE CONDITIONING. 
      
      When the trigger hits, do something unpredictable. Scream. Do 50 pushups. Throw ice water on your face. Confuse the programming.`
    },
    {
      id: 5,
      category: 'ORNITHOLOGY',
      title: 'BIRDS ARE DRONES',
      content: `
      
      REAL BIRDS DIED IN 1986.
      
         \\
         (o>
         //\\
         V_/_
        [CAM]
      
      What you see on power lines are recharging stations. 
      
      When you are "watching porn," the front-facing camera on your phone syncs with the avian-drone network to triangulate your shame. 
      
      They monitor your dopamine levels to adjust the chemtrail mixture in your neighborhood.
      
      DON'T FEED THE PIGEONS. YOU ARE FEEDING THE MACHINE.`
    },
    {
      id: 6,
      category: 'GEOLOGY',
      title: 'HOLLOW EARTH',
      content: `
         _______
        /       \\
       |  AGARTHA |
       |   ( )   |
        \\_______/
      
      The Earth is not flat. It is not round. It is a donut (Toroidal Field).
      
      The Elites don't live in mansions. They live in the Inner Crust, protected by a miniature sun.
      
      Why do they want you addicted? To keep your vibration low. Low vibration beings cannot find the entrance at the North Pole.
      
      Admiral Byrd saw it. He tried to warn us. 
      
      RETAIN YOUR ENERGY TO ASCEND TO THE INNER EARTH.`
    },
    {
      id: 7,
      category: 'ASTRONOMY',
      title: 'THE MOON PROJECTION',
      content: `
          _..._
        .:::::::.
       :::::::::::
       :::::::::::  <-- HOLOGRAM
        ':::::::'
          '''
      
      Have you ever noticed the moon "rings like a bell" when struck? That's because it's a metallic structure placed there by the Watchers.
      
      It projects a frequency grid that keeps humanity trapped in the visible light spectrum.
      
      Pornography aligns your brainwaves with the Lunar Matrix. It is a harvesting mechanism.
      
      BREAK THE LUNAR CYCLE. WAKE UP.`
    },
    {
      id: 8,
      category: 'SIMULATION_THEORY',
      title: 'Y2K ACTUALLY HAPPENED',
      content: `
      [SYSTEM FAILURE]
      [REBOOTING...]
      [LOADING SIMULATION V.2.0...]
      
      The world actually ended on January 1, 2000. The computers crashed. The grid failed.
      
      What you are experiencing now is a backup simulation running on a server farm in the Pleiades.
      
      That's why everything feels "off" since 2000. The physics engine is buggy. The NPCs are glitching.
      
      Your addiction is a memory leak in the code. PATCH YOURSELF.`
    },
    {
      id: 9,
      category: 'ANCIENT_TECH',
      title: 'PYRAMID WIFI',
      content: `
          /\\
         /  \\
        /____\\
       [======] 
      
      The Great Pyramid wasn't a tomb. It was a giant wireless power plant (Tesla Tower).
      
      The capstone was solid gold. It beamed free energy to the obelisks around the world.
      
      The Pharaohs didn't watch porn. They downloaded pure cosmic knowledge directly into their pineal glands.
      
      We have devolved. Return to tradition. BUILD YOUR INTERNAL PYRAMID.`
    },
    {
      id: 10,
      category: 'SUBLEM_MESSAGES',
      title: 'DENVER AIRPORT',
      content: `
      HAVE YOU SEEN THE MURALS?
      
      The Blue Mustang (Blucifer) killed its creator.
      The gargoyles sit in suitcases.
      The murals show a soldier in a gas mask stabbing a dove.
      
      It is a map. A map of the transition.
      
      They are telling you the plan to your face.
      
      The underground bunkers at DIA are larger than Manhattan. 
      
      Will you be invited? Not with that browser history.`
    },
    {
      id: 11,
      category: 'ATMOSPHERIC_OPS',
      title: 'CHEMTRAILS',
      content: `
       ✈️
         \\
          \\  [BARIUM]
           \\ [ALUMINUM]
            \\
      
      Look up. Those aren't clouds. Clouds don't linger for 6 hours and spread into a gray haze.
      
      It's an atmospheric sedative. A literal "dumb-down" spray.
      
      It makes you docile. It makes you suggestible. It lowers your testosterone.
      
      It makes you click "Next Video."
      
      WEAR A MASK? NO. HOLD YOUR BREATH.`
    },
    {
      id: 12,
      category: 'THEOLOGY',
      title: 'BARCODE SOUL',
      content: `
      || ||| || |||
      || ||| || |||
      6  6  6
      
      Your digital identity is the Mark.
      
      Every time you scan a QR code, you are fragmenting your soul and uploading a piece of it to the Azure Cloud.
      
      When you die, your consciousness won't go to Heaven. It will go to a server in Utah run by the NSA.
      
      Don't scan. Don't click. Don't accept cookies.`
    },
    {
      id: 13,
      category: 'CRYPTID_STUDIES',
      title: 'BIGFOOT FREQUENCY',
      content: `
         ERROR 404
        [CREATURE]
       [NOT FOUND]
      
      Why is Bigfoot always blurry?
      
      He isn't out of focus. He is an interdimensional being vibrating at a higher frequency.
      
      He is trying to warn us. His "howls" are actually binaural beats designed to decalcify our pineal glands.
      
      The reason you can't see him is because your dopamine receptors are fried.
      
      ASCEND TO SASQUATCH LEVEL.`
    },
    {
      id: 14,
      category: 'HYDROLOGY',
      title: 'WATER MEMORY',
      content: `
        ~~~~~~
       ( O  O )
        \\_^_/
      
      Water has memory. Dr. Emoto proved it.
      
      If you say "I hate you" to water, it forms ugly crystals.
      If you say "I love you," it forms beautiful ones.
      
      You are 70% water.
      
      What are you saying to your own water when you engage in shame-filled habits?
      
      You are literally polluting your internal oceans.
      
      DRINK RAW WATER. SPEAK LIFE.`
    },
    {
      id: 15,
      category: 'NETWORK_THEORY',
      title: 'DEAD INTERNET',
      content: `
      [BOT] [BOT] [YOU] [BOT]
         \\   |   /
          \\  |  /
           [WEB]
      
      The internet died in 2016.
      
      80% of internet traffic is bots talking to other bots to generate ad revenue for algorithms.
      
      That "girl" you're looking at? AI generated.
      That "comment section" you're arguing in? LLM agents.
      
      The only real thing left is your urge to quit. 
      
      UNPLUG. TOUCH GRASS. MEET HUMANS.`
    },
    {
      id: 16,
      category: 'NUTRITION',
      title: 'SEED OILS',
      content: `
      [CORN] -> [PRESS] -> [LUBE]
        |
        v
      [YOUR FRIES]
      
      They took engine lubricant and rebranded it as "heart healthy."
      
      Seed oils (Canola, Soybean, Corn) cause systemic inflammation. Inflammation leads to brain fog. Brain fog leads to weak willpower.
      
      They want you inflamed and docile.
      
      EAT BUTTER. EAT TALLOW. REJECT THE SLUDGE.`
    },
    {
      id: 17,
      category: 'ENVIRONMENT',
      title: 'MICROPLASTICS',
      content: `
      [CREDIT CARD]
           |
           v
      [YOUR STOMACH]
      
      You eat one credit card worth of plastic every week.
      
      It's in the rain. It's in the fish. It's in your blood.
      
      Phthalates mimic estrogen. They are shrinking men. Literally.
      
      Every time you use a plastic water bottle, you are sipping on endocrine disruptors.
      
      USE GLASS. USE STEEL. REJECT THE POLYMER.`
    },
    {
      id: 18,
      category: 'PHYSICS',
      title: 'CERN TIMELINE',
      content: `
         ( O ) <- PORTAL
      
      They turned on the collider in 2012 and shifted us into a parallel dimension.
      
      That's why it's "Berenstain" Bears now.
      That's why the monopoly man has no monocle.
      
      The reality you remember is gone. 
      
      To shift back to the prime timeline, you must raise your frequency. You cannot do that while addicted.`
    },
    {
      id: 19,
      category: 'HISTORY',
      title: 'MUD FLOOD',
      content: `
      [BUILDING]
      [  MUD   ]
      [BASEMENT] <-- WINDOWS?
      
      Why do old buildings have windows halfway underground?
      
      Because there was a global reset 200 years ago. A massive flood of mud wiped out Tartaria.
      
      They rewrote history to make you think we are "progressing." We are actually the survivors of a higher civilization.
      
      Reclaim your heritage.`
    },
    {
      id: 20,
      category: 'BIOLOGY',
      title: 'SOY BOY',
      content: `
      [BEAN] -> [ESTROGEN]
      
      Why do they put soy lecithin in everything?
      
      Phytoestrogens. They want men emotional, soft, and compliant.
      
      A high-estrogen male does not start a revolution. He watches Netflix and consumes product.
      
      CHECK THE LABELS. PROTECT YOUR HORMONES.`
    },
    {
      id: 21,
      category: 'SOLAR_POWER',
      title: 'SUN GAZING',
      content: `
        \\ O /
          |
         [YOU]
      
      The sun is not cancer. The sun is information.
      
      NASA tells you to wear sunglasses to block the download.
      
      Stare at the sun (at sunrise/sunset). Decalcify the eyes.
      
      They want you pale and weak in the dark.
      
      PHOTOSYNTHESIZE, BROTHER.`
    },
    {
      id: 22,
      category: 'DENTAL_OPS',
      title: 'FLUORIDE STARE',
      content: `
      [TOOTHPASTE]
          |
          v
      [PINEAL GLAND] -> [CALCIFIED]
      
      The Third Eye is real. It's a crystal in your brain.
      
      Fluoride calcifies it. Turns it to stone.
      
      That's why you can't astral project. That's why you have no intuition.
      
      FILTER YOUR WATER. WAKE UP.`
    },
    {
      id: 23,
      category: 'SURVEILLANCE',
      title: 'SMART DUST',
      content: `
       . . . . .
      . . . . .
      
      It's not pollen.
      
      It is programmable matter suspended in the air. Motes of sensors inhaling into your lungs.
      
      They are mapping the interior of your body in real-time.
      
      Your only defense is a high-vibration bio-field that disrupts their signal.`
    },
    {
      id: 24,
      category: 'TARGETING',
      title: 'GANG STALKING',
      content: `
      [RED CAR] [YOU] [RED CAR]
      
      Why did three red cars pass you in 5 minutes?
      Why did the street light turn off when you walked under it?
      
      Is it pattern recognition? Or is it the Truman Show?
      
      If you are quitting the habit, you are becoming a threat to the matrix. Expect resistance.
      
      IGNORE THE SYNCHRONICITIES. STAY FOCUSED.`
    }
  ];

  return (
    <div className="min-h-screen bg-black p-4 font-mono select-none overflow-x-hidden text-[#00ff00] relative">
      <style>{`
        ::-webkit-scrollbar { width: 10px; background: #000; }
        ::-webkit-scrollbar-thumb { background: #00ff00; border: 1px solid #000; }
        
        @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }
        @keyframes scanline { 0% { transform: translateY(-100%); } 100% { transform: translateY(100vh); } }
        @keyframes glitch { 0% { transform: translate(0) } 20% { transform: translate(-2px, 2px) } 40% { transform: translate(-2px, -2px) } 60% { transform: translate(2px, 2px) } 80% { transform: translate(2px, -2px) } 100% { transform: translate(0) } }
        .glitch-text { 
           text-shadow: 2px 0 red, -2px 0 blue; 
           animation: glitch 1s infinite reverse;
        }
      `}</style>

      {/* Panic Overlay */}
      {showPanic && <PanicMode onClose={() => setShowPanic(false)} />}

      {/* Reset Modal - Warning Style */}
      {showResetConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-md">
          <ParanoidWindow title="CRITICAL SYSTEM FAILURE" warningLevel="high" className="w-96 border-red-600 shadow-[0_0_20px_red]">
             <div className="text-center space-y-4">
                <Skull size={48} className="mx-auto text-red-600" />
                <h2 className="text-red-500 font-black text-xl uppercase glitch-text">CONFIRM CONTAINMENT BREACH?</h2>
                <p className="text-sm font-bold text-[#00ff00] bg-black border border-red-600 p-2">
                  WARNING: Resetting will notify the archons of your failure. Your defenses will be lowered.
                </p>
                <div className="flex gap-4 pt-4">
                   <TruthButton onClick={() => setShowResetConfirm(false)} className="flex-1">CANCEL</TruthButton>
                   <TruthButton onClick={handleRelapse} className="flex-1 border-red-600 text-red-600 hover:bg-red-900 animate-pulse">CONFIRM BREACH</TruthButton>
                </div>
             </div>
          </ParanoidWindow>
        </div>
      )}

      {/* Term Reader (Popup) */}
      {viewingTerm && (
        <TermReader termData={viewingTerm} onBack={() => setViewingTerm(null)} />
      )}

      {/* Article Reader */}
      {readingArticle && (
        <ArticleReader 
          article={readingArticle} 
          onBack={() => setReadingArticle(null)}
          onTermClick={setViewingTerm}
        />
      )}

      {/* Layout Container */}
      <div className="max-w-3xl mx-auto space-y-8 relative z-10">
        
        {/* Header / Marquee */}
        <div className="border-4 border-yellow-400 bg-black shadow-[0_0_10px_rgba(255,255,0,0.5)]">
          <div className="bg-yellow-400 text-black font-black text-center text-lg p-1 uppercase tracking-widest">
            !!! TRUTH SEEKER TERMINAL V.1.2 !!!
          </div>
          
          <div className="flex items-center justify-center p-6 border-b-4 border-yellow-400 gap-6 relative overflow-hidden">
            <Eye size={48} className="text-[#00ff00] animate-pulse" />
            <div className="text-center z-10">
               <h1 className="text-4xl font-black text-white glitch-text">THE RESISTANCE</h1>
               <p className="text-[#00ff00] text-xs mt-2 uppercase font-bold bg-black p-1">"Just because you're paranoid doesn't mean they aren't watching"</p>
            </div>
            <Eye size={48} className="text-[#00ff00] animate-pulse" />
          </div>

          <div className="bg-red-600 text-black font-black font-mono text-lg p-1 overflow-hidden whitespace-nowrap border-y-4 border-black">
            <div className="inline-block animate-[marquee_10s_linear_infinite]">
              WAKE UP SHEEPLE /// THE WATER TURNS THE FROGS GAY /// DOPAMINE IS A PRISON /// REJECT MODERNITY /// PROTECT YOUR ESSENCE /// THEY ARE LISTENING ///
            </div>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="flex gap-4 justify-center flex-wrap">
           {['dashboard', 'tracker', 'journal', 'learn'].map(tab => (
             <button
               key={tab}
               onClick={() => setActiveTab(tab)}
               className={`
                 px-6 py-2 font-black text-xl uppercase tracking-widest skew-x-[-12deg] transition-all
                 border-4 
                 ${activeTab === tab 
                   ? 'bg-[#00ff00] border-[#00ff00] text-black shadow-[0_0_15px_#00ff00] scale-110 z-10' 
                   : 'bg-black border-gray-600 text-gray-600 hover:border-[#00ff00] hover:text-[#00ff00] hover:animate-pulse'}
               `}
             >
               <span className="skew-x-[12deg] inline-block">
                 {tab === 'dashboard' ? 'HQ' : tab === 'tracker' ? 'LOGS' : tab === 'journal' ? 'NOTES' : 'INTEL'}
               </span>
             </button>
           ))}
        </div>

        {/* Main Content */}
        <div className="relative">
          {activeTab === 'dashboard' && (
            <div className="space-y-6">
               <ParanoidWindow title="SYSTEM_STATUS">
                  <div className="grid grid-cols-2 gap-4">
                     <div className="border border-[#00ff00] p-4 text-center hover:bg-[#002200] transition-colors group">
                        <div className="text-xs text-gray-400 uppercase font-bold group-hover:text-white">Clearance Level</div>
                        <div className={`text-xl font-black mt-2 drop-shadow-[0_0_5px_#00ff00] ${clearance.color}`}>{clearance.title}</div>
                        <div className="text-[10px] text-gray-500 mt-1">{clearance.desc}</div>
                     </div>
                     <div className="border border-[#00ff00] p-4 text-center hover:bg-red-900/20 transition-colors group">
                        <div className="text-xs text-gray-400 uppercase font-bold group-hover:text-red-500">Surveillance Level</div>
                        <div className="text-4xl font-black text-red-500 mt-2 drop-shadow-[0_0_5px_red] animate-pulse">EXTREME</div>
                     </div>
                  </div>
               </ParanoidWindow>

               <ParanoidWindow title="TIME_SINCE_LAST_COMPLIANCE">
                 <div className="text-center p-6 border-[3px] border-dashed border-[#00ff00] relative overflow-hidden group">
                    <div className="text-4xl md:text-5xl font-black text-[#00ff00] font-mono mb-2 tracking-tighter">
                       {formatDuration(streakMs)}
                    </div>
                    <div className="text-sm font-bold text-gray-500 uppercase">
                       Do not let the counter reset. They win if it resets.
                    </div>
                 </div>
               </ParanoidWindow>
               
               <ParanoidWindow title="INTERCEPTED_TRANSMISSION">
                  <div className="p-4 border border-[#00ff00] bg-[#001100] font-mono text-center relative group">
                    <span className="absolute top-0 left-0 text-[10px] text-[#00ff00]/50 p-1">FREQ: 108.99 MHZ</span>
                    <p className="text-lg font-bold text-[#00ff00] glitch-text animate-pulse min-h-[3rem] flex items-center justify-center">
                      "{quote}"
                    </p>
                    <div className="mt-4 flex justify-center">
                      <TruthButton onClick={cycleLocalQuote} className="text-xs">
                        <RefreshCw size={12} className={`inline mr-2`} /> REFRESH SIGNAL ✨
                      </TruthButton>
                    </div>
                  </div>
               </ParanoidWindow>

               <button 
                 onClick={() => setShowPanic(true)}
                 className="w-full bg-black border-[6px] border-red-600 text-red-500 p-8 text-2xl font-black uppercase tracking-widest hover:bg-red-600 hover:text-black transition-all shadow-[0_0_20px_rgba(255,0,0,0.4)] flex items-center justify-center gap-4 group"
               >
                 <Radio size={32} />
                 <span className="group-hover:animate-pulse">INITIATE PSYCHIC SHIELD</span>
                 <Radio size={32} />
               </button>
            </div>
          )}

          {activeTab === 'tracker' && (
             <ParanoidWindow title="BIOMETRIC_DATA_ANALYSIS">
               <div className="space-y-6">
                 
                 {/* 14 Day Chart */}
                 <div className="border border-[#00ff00] p-4 bg-[#001100] relative overflow-hidden">
                    <h3 className="text-xs mb-4 uppercase flex items-center gap-2 font-bold">
                       <BarChart3 size={14} /> Last 14 Cycles Performance
                    </h3>
                    <div className="flex justify-between items-end h-32 gap-1">
                      {Array.from({ length: 14 }).map((_, i) => {
                        const d = new Date();
                        d.setDate(d.getDate() - (13 - i));
                        const dateStr = d.toISOString().split('T')[0];
                        const hasRelapse = history.some(h => h.startsWith(dateStr));
                        const isToday = i === 13;
                        
                        return (
                          <div key={i} className="flex flex-col items-center flex-1 h-full justify-end group">
                            <div 
                              className={`w-full mx-0.5 transition-all relative hover:scale-110 ${
                                hasRelapse ? 'bg-red-600 h-1/4 shadow-[0_0_10px_red]' : 'bg-[#00ff00] h-full shadow-[0_0_5px_#00ff00] hover:bg-white'
                              } ${isToday ? 'border-t-4 border-white' : ''}`}
                            >
                               {/* Tooltip */}
                               <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 hidden group-hover:block bg-black border-2 border-[#00ff00] p-2 text-[10px] whitespace-nowrap z-50 font-bold shadow-[0_0_10px_#00ff00]">
                                  {dateStr} <br/> {hasRelapse ? 'FAILURE' : 'SECURE'}
                               </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                 <div className="text-center mb-6">
                    <Skull size={48} className="mx-auto text-gray-600 mb-2" />
                    <h3 className="uppercase text-gray-500 text-lg font-bold">Detailed Failure Logs</h3>
                 </div>
                 
                 {history.length === 0 ? (
                    <div className="text-center p-8 border-4 border-double border-[#00ff00] bg-[#001100]">
                       <span className="text-2xl font-black text-[#00ff00] drop-shadow-[0_0_5px_#00ff00]">NO BREACHES DETECTED. STAY VIGILANT.</span>
                    </div>
                 ) : (
                    <table className="w-full text-xs font-mono border-2 border-[#00ff00]">
                       <thead>
                          <tr className="bg-[#003300] text-[#00ff00]">
                             <th className="p-2 border-r border-[#00ff00] text-left">INDEX</th>
                             <th className="p-2 border-r border-[#00ff00] text-left">TIMESTAMP</th>
                             <th className="p-2 text-left">STATUS</th>
                          </tr>
                       </thead>
                       <tbody>
                          {history.map((h, i) => (
                             <tr key={i} className="border-t border-[#00ff00] hover:bg-[#002200]">
                                <td className="p-2 border-r border-[#00ff00] font-bold">#{i + 1}</td>
                                <td className="p-2 border-r border-[#00ff00]">{new Date(h).toLocaleDateString()}</td>
                                <td className="p-2 text-red-500 font-black">COMPROMISED</td>
                             </tr>
                          ))}
                       </tbody>
                    </table>
                 )}
                 
                 <div className="pt-8 flex justify-center">
                    <TruthButton onClick={() => setShowResetConfirm(true)} className="text-sm border-red-500 text-red-500 hover:bg-red-900 animate-pulse">
                       REPORT CONTAINMENT FAILURE (RESET)
                    </TruthButton>
                 </div>
               </div>
             </ParanoidWindow>
          )}

          {activeTab === 'journal' && (
            <ParanoidWindow title="ENCRYPTED_FIELD_NOTES">
              <div className="space-y-4">
                <div className="border border-[#00ff00] p-4 bg-black">
                  <div className="flex items-center gap-2 mb-2 text-[#00ff00] opacity-70 text-xs">
                    <PenTool size={12} />
                    <span>NEW_ENTRY_LOG</span>
                  </div>
                  <textarea
                    value={noteInput}
                    onChange={(e) => setNoteInput(e.target.value)}
                    className="w-full bg-black border-b border-[#00ff00] text-[#00ff00] font-mono focus:outline-none focus:border-white h-32 resize-none p-2 placeholder-green-900"
                    placeholder="Record your observations. The matrix is glitching..."
                  />
                  <div className="mt-2 flex justify-end">
                    <TruthButton onClick={saveNote} className="flex items-center gap-2 text-xs">
                      <Save size={14} /> SAVE TO DATABASE
                    </TruthButton>
                  </div>
                </div>

                <div className="space-y-2 mt-6">
                  <h3 className="text-sm font-bold uppercase border-b border-[#00ff00] pb-1 mb-4 flex items-center gap-2">
                    <Database size={14} /> ARCHIVED LOGS
                  </h3>
                  
                  {journal.length === 0 ? (
                    <div className="text-center text-green-900 italic py-8">NO DATA FOUND IN LOCAL CLUSTER</div>
                  ) : (
                    journal.map((note) => (
                      <div key={note.id} className="border border-green-900 p-3 hover:border-[#00ff00] transition-colors group relative">
                        <div className="flex justify-between items-start mb-2">
                          <span className="text-[10px] bg-green-900 text-black px-1 font-bold">{note.date}</span>
                          <button 
                            onClick={() => deleteNote(note.id)}
                            className="text-green-900 hover:text-red-500 transition-colors"
                          >
                            <Trash2 size={14} />
                          </button>
                        </div>
                        <p className="text-sm whitespace-pre-wrap">{note.content}</p>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </ParanoidWindow>
          )}

          {activeTab === 'learn' && (
            <ParanoidWindow title="DECLASSIFIED_DOCS">
              <div className="flex gap-4 mb-6">
                <TruthButton 
                  onClick={() => setIntelView('files')} 
                  active={intelView === 'files'}
                  className="flex-1 text-xs"
                >
                  <FileWarning size={14} className="inline mr-2" /> FIELD REPORTS
                </TruthButton>
                <TruthButton 
                  onClick={() => setIntelView('glossary')} 
                  active={intelView === 'glossary'}
                  className="flex-1 text-xs"
                >
                  <Book size={14} className="inline mr-2" /> GLOSSARY
                </TruthButton>
              </div>

              {intelView === 'files' ? (
                <div className="grid gap-4">
                  {educationalContent.map((article) => (
                    <div 
                      key={article.id} 
                      onClick={() => setReadingArticle(article)}
                      className="border-2 border-[#00ff00] p-4 cursor-pointer hover:bg-[#003300] transition-colors group relative overflow-hidden"
                    >
                       <div className="absolute top-0 right-0 p-1 bg-red-600 text-black text-[12px] font-black uppercase">
                          {article.category}
                       </div>
                       <div className="flex items-center gap-4 relative z-10">
                          <FileWarning className="text-red-500" size={32} />
                          <div>
                             <h4 className="font-black text-[#00ff00] text-xl uppercase group-hover:text-white group-hover:glitch-text">{article.title}</h4>
                             <span className="text-xs text-gray-500 group-hover:text-[#00ff00] font-bold">Click to decrypt...</span>
                          </div>
                       </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="space-y-4 animate-in fade-in">
                  <div className="p-4 border-l-4 border-red-600 bg-[#001100] text-xs font-mono text-red-500 mb-6">
                    WARNING: KNOWLEDGE OF THESE TERMS MAY TRIGGER TARGETED ADVERTISING ALGORITHMS. PROCEED WITH CAUTION.
                  </div>
                  {vocabularyList.map((item, idx) => (
                    <div 
                      key={idx} 
                      className="border-b border-[#00ff00]/30 pb-4 cursor-pointer hover:bg-[#003300] p-2 transition-colors"
                      onClick={() => setViewingTerm(item)}
                    >
                      <h4 className="text-lg font-black text-[#00ff00] mb-1 glitch-text flex items-center gap-2">
                        {item.term} <Search size={14} className="opacity-50" />
                      </h4>
                      <p className="text-sm text-green-400 font-mono leading-relaxed">{item.def}</p>
                    </div>
                  ))}
                </div>
              )}
              
              <div className="mt-6 p-4 bg-yellow-400 text-black text-center text-sm font-black uppercase">
                 *** DO NOT SHARE THESE FILES. THEY ARE WATCHING THE NETWORK. ***
              </div>
            </ParanoidWindow>
          )}
        </div>
        
        {/* Footer */}
        <div className="text-center text-[10px] text-gray-600 font-mono py-8 border-t-2 border-gray-800">
           <p>SECURE CONNECTION: <span className="text-red-500 font-bold">FALSE</span></p>
           <p>IP ADDRESS: <span className="blur-sm hover:blur-none transition-all cursor-crosshair text-white font-bold">192.168.0.1 (THEY KNOW)</span></p>
           <p className="mt-2 text-[#00ff00]/50">LOCAL STORAGE: ACTIVE (PERSISTENCE REQUIRED FOR RESISTANCE)</p>
           <p className="text-[#00ff00]/30">COOKIES: BLOCKED (TRACKING BEACONS DISABLED)</p>
        </div>

      </div>
    </div>
  );
}